source 'https://cdn.cocoapods.org/'
use_frameworks!

platform :ios, '13.0'

target 'ResumableCombine_Example' do
  pod 'ResumableCombine', :path => '../'

  target 'ResumableCombine_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 4.0'
    pod 'Nimble', '~> 9.0'
  end
end
